//Friends Profile Data
export const FriendsProfileData = [
    {
        id: 'Noodles',
        nickname: '우리동네',
        StateMessage:'@우리동네_공식계정',
        profileImage: require('../../storage/images/logo.jpg'),
        posts: 56,
        followers: 9451,
        following: 0,
        follow: false,
    },
    {
        id: 'KimJiMin',
        nickname: '김지민',
        StateMessage:'@JiMin',
        profileImage: require('../../storage/images/profile1.jpg'),
        posts: 56,
        followers: 123,
        following: 456,
        follow: false,
    },
    {
        id: 'JungSeBin',
        nickname: '정세빈',
        StateMessage:'@SeBin',
        profileImage: require('../../storage/images/profile2.jpg'),
        posts: 56,
        followers: 484,
        following: 784,
        follow: false,
    },
    {
        id: 'ChoYeonJu',
        nickname: '조연주',
        StateMessage:'@YoenJu',
        profileImage: require('../../storage/images/profile3.jpg'),
        posts: 56,
        followers: 568,
        following: 984,
        follow: false,
    },
    {
        id: 'ChoiSeongYong',
        nickname: '최승용',
        StateMessage:'@SeongYong',
        profileImage: require('../../storage/images/profile4.jpg'),
        posts: 56,
        followers: 684,
        following: 691,
        follow: false,
    },
]

//Post Data
export const PostData = [
    {
        id: 'JungBBang',
        Nickname: "빵이",
        StateMessage:'@J_bread',
        postPersonImage: require("../../storage/images/fig.jpg"),
        posts: 56,
        followers: 684,
        following: 691,
        follow: false,
        postImage: require("../../storage/images/post1.png"),
        location: "경기도 수원시 망포동",
        textmsg: "안냐세염^^",
        distance: "대략 130m",
        likes: 765,
        isLiked: false,
        bookmarked: false,
        closed: false,
    },
    {
        id: 'JungSeBin',
        Nickname: "세빈",
        StateMessage:'@SeBin',
        postPersonImage: require("../../storage/images/profile1.jpg"),
        posts: 56,
        followers: 684,
        following: 691,
        follow: false,
        postImage: require("../../storage/images/post22.jpg"),
        location: "경기도 수원시 화서동",
        textmsg: "안녕 난 세빈이야",
        distance: "대략 270m",
        likes: 81,
        isLiked: false,
        bookmarked: false,
        closed: false,
    },
    {
        id: 'JJangGu',
        Nickname: "짱구",
        StateMessage:'@JJangGu',
        postPersonImage: require("../../storage/images/profile2.jpg"),
        posts: 56,
        followers: 684,
        following: 691,
        follow: false,
        postImage: require("../../storage/images/post2.png"),
        location: "경기도 수원시 떡잎마을",
        textmsg: "안녕 난 짱구야",
        distance: "대략 560m",
        likes: 99,
        isLiked: false,
        bookmarked: false,
        closed: false,
    },
    {
        id: 'JungBBang',
        Nickname: "빵이",
        StateMessage:'@J_bread',
        postPersonImage: require("../../storage/images/fig.jpg"),
        posts: 56,
        followers: 684,
        following: 691,
        follow: false,
        postImage: require("../../storage/images/post3.jpg"),
        location: "경기도 수원시 망포동",
        textmsg: "안냐세염^^",
        distance: "대략 130m",
        likes: 765,
        isLiked: false,
        bookmarked: false,
        closed: false,
    },
    {
        id: 'JungBBang',
        Nickname: "빵이",
        StateMessage:'@J_bread',
        postPersonImage: require("../../storage/images/fig.jpg"),
        posts: 56,
        followers: 684,
        following: 691,
        follow: false,
        postImage: require("../../storage/images/profile6.jpg"),
        location: "경기도 수원시 망포동",
        textmsg: "안냐세염^^",
        distance: "대략 130m",
        likes: 765,
        isLiked: false,
        bookmarked: false,
        closed: false,
    },
]