//Friends Profile Data
export const FriendsProfileData = [
    {
        id: 'Noodles',
        nickname: '우리동네',
        StateMessage:'@우리동네_공식계정',
        profileImage: require('../../storage/images/logo.jpg'),
        posts: 56,
        followers: 9451,
        following: 0,
        follow: false,
    },
    {
        id: 'KimJiMin',
        nickname: '김지민',
        StateMessage:'@JiMin',
        profileImage: require('../../storage/images/profile1.jpg'),
        posts: 56,
        followers: 123,
        following: 456,
        follow: false,
    },
    {
        id: 'JungSeBin',
        nickname: '정세빈',
        StateMessage:'@SeBin',
        profileImage: require('../../storage/images/profile2.jpg'),
        posts: 56,
        followers: 484,
        following: 784,
        follow: false,
    },
    {
        id: 'ChoYeonJu',
        nickname: '조연주',
        StateMessage:'@YoenJu',
        profileImage: require('../../storage/images/profile3.jpg'),
        posts: 56,
        followers: 568,
        following: 984,
        follow: false,
    },
    {
        id: 'ChoiSeongYong',
        nickname: '최승용',
        StateMessage:'@SeongYong',
        profileImage: require('../../storage/images/profile4.jpg'),
        posts: 56,
        followers: 684,
        following: 691,
        follow: false,
    },
]